# Numpy 

In [1]:
import numpy as np

In [11]:
# Creaing Array

arr  = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# Dimension of array

print(arr.ndim)

2


In [13]:
# Shape of array

print(arr.shape)

(2, 4)


In [14]:
# Type of array

print(type(arr))

<class 'numpy.ndarray'>


In [15]:
# location of array at memory

print(arr.data)

## Basic Function

In [51]:
# Transpose

print(arr.transpose())

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [63]:
# Universal Array

arr1 = np.arange(10).reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [64]:
# Square root

arr2 = np.sqrt(arr1)
print(arr2)

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


In [65]:
# Exponential

arr3 = np.sqrt(arr1)
print(arr3)

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


In [85]:
# Random Array Generator

arr4 = np.random.rand(10)
print(arr4)

[0.5031273  0.62068905 0.08891395 0.14682587 0.11768726 0.23636345
 0.62489964 0.80231315 0.49342245 0.24438573]


In [86]:
# Maximum
arr5 = np.maximum(arr2,arr3)
print(arr5)

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


## Activity 1

### Finding out BMI

In [16]:
# Calculate BMI of cricketers

# height
height_in = [72,64,56,89,92,105,84,52,79,100]

# weight
weight_pound = [120,158,130,180,187,190,177,152,165,177]

In [17]:
# Creating NP array

height = np.array(height_in)
weight = np.array(weight_pound)

# Shape
print(height.shape, weight.shape)

(10,) (10,)


In [28]:
# Converting inch to cm

print("Previous Array: ",height)
height = height*0.25
print("Updated Array: ",height)

Previous Array:  [ 72  64  56  89  92 105  84  52  79 100]
Updated Array:  [18.   16.   14.   22.25 23.   26.25 21.   13.   19.75 25.  ]


In [18]:
# Converting pounds to kg

print("Previous Array: ",weight)
weight = weight*0.45
print("Updated Array: ",weight)

Previous Array:  [120 158 130 180 187 190 177 152 165 177]
Updated Array:  [54.   71.1  58.5  81.   84.15 85.5  79.65 68.4  74.25 79.65]


In [29]:
# Calculate BMI

# Weight/height **2

bmi = (weight/height) **2

print(bmi)

[ 9.         19.74691406 17.46045918 13.25287211 13.38605388 10.60897959
 14.38576531 27.68378698 14.13379266 10.150596  ]


In [30]:
# Values Greater than 21
print(bmi[bmi > 21])

[27.68378698]


In [32]:
# Values Less than 21
print(bmi[bmi < 21])

[ 9.         19.74691406 17.46045918 13.25287211 13.38605388 10.60897959
 14.38576531 14.13379266 10.150596  ]


## Stats Function 

In [90]:
# Mean
print(np.mean(height))
print(np.mean(weight))

19.825
73.62


In [91]:
# Median
print(np.median(height))
print(np.median(weight))

20.375
76.95


In [89]:
# Sum
print(np.sum(height))
print(np.sum(weight))

198.25
736.2


In [92]:
# Standard Deviation
print(np.std(height))
print(np.std(weight))

4.288137707676842
10.132896920427052


In [95]:
# Correlation and Coefficient
print(np.corrcoef(height))
print(np.corrcoef(weight))

1.0
1.0


### Boolean Array

In [96]:
bools = [False, True, True, False, True]

In [98]:
# Converting in array
b = np.array(bools)
print(b)

[False  True  True False  True]


In [99]:
# Sum
print(np.sum(3))

3


In [103]:
# Any Method
print(np.any(b))

True


In [104]:
# All Method
print(np.all(b))

False


## Extra

In [106]:
# Question

# Global

x_value = -1
y_value = 1

x=0
y=0


def l():
    global x_value
    if x_value > 0:
        # Chnaging Direction
        x_value -= 0.5
        return x_value
    # Chnaging Direction
    x_value += 0.5
    return x_value


def r():
    global y_value
    if y_value == 1:
        # Chnaging Direction
        y_value = -1
        return y_value
    # Chnaging Direction
    y_value = 1
    return y_value
        
    
def g():
    if x_value == 1:
        global x
        x+=x_value
    else:
        global y
        y+=y_value
    print(x,y)
        

In [110]:
# Default values
x=0;y=0;x_value = -1;y_value = 1

# Operation
g()
g()
l()
l()
l()
g()

0 1
0 2
0 3
